### PR TITLE
error handler

### PR DESCRIPTION
**Pull request by shikamu**
Hello again,

I don't know if there's already another way to do this but I need to have custom error handling for my project for some cases where several different things can go wrong so that we can display it to the user the way we handle other errors.

example use case:

test.vue
```
    <a v-auth-href="{downloadingText: 'téléchargement en cours', overrideInnerHtml: false, errorHandler: exportErrorHandler}" 
         :href="`${apiURL}/hours/exportAllUserForYearData?fromDate=${searchPeriodFrom.toISOString()}`" 
         class="links-row action-base"
    >
```
test.ts
```
  public get exportErrorHandler () {
    return async (e) => {
      if (e?.response?.data) {
        e.response.data.text().then(async errs => {
          const obj = {
            status: 400,
            data: JSON.parse(errs)
          }
          const res = await ErrorService.handleError(obj)
          this.errorMessages = errs
        })
      }
    }
  }
```

### CODE REVIEW

**Comment by nachodd** [comment]
Hello @shikamu! Nice to read you here again. Nice feature, I didn't think about it! It would be nice to have this option as a general option in the initialization (and this could be overrided as an inline option in the directive). 
What do you think?
I could work it, but that would be the next week, as I'm on vacation these days. Let me know what you think!

**Comment by shikamu** [comment]
Hi @nachodd !

What do you mean exactly ? I think the current implementation from my PR already supports what you are referring to. I'm able to do this:
```
const options = {
  token: () => authService.getAccessToken(),
  removeDelay: 100,
  errorHandler: (e) => {
    console.log('bam: ', e)
  }
}
Vue.use(VueAuthHref, options)
```

and it will call that handler. I am also able to override it with the inline option in the directive directly as per my first post :) So I think both ways are already supported or did you mean anything else ?

**Comment by nachodd** [comment]
Oh sorry... I was referring exactly to that. I wasn't able to check it correctly, as I didn't have my laptop 😅
Let me a few hours and I'll be merging this and making a new release 👍👍
Thanks again man!

**Comment by shikamu** [comment]
no problem dude, take your time it can also wait until next week :)

**Comment by shikamu** [comment]
@nachodd  did you have any time to check that PR out yet ? ;)

**Comment by nachodd** [comment]
Today I'm returning from my vacations. I'll be checking on this by tomorrow for sure. I'll let you know here 👍

**Review by nachodd — APPROVED** [review]

**Comment by nachodd** [comment]
There it is, i just released 1.4.0 version. Thanks @shikamu!

**Pull request merged**
